### ISSUE TITLE
probably fake

### ISSUE THREAD

**Issue by zihasz** [FaxHack/Abyss-Client-Leak-Full-Version#2]
no way you cracked fucking rocket drm 🤣
you cant even crack a simple auth probably and rocket is a fucking native drm lolll

**Comment by zihasz** [comment]
ok you didnt even crack anything 😆 😆 😆 😆

**Comment by MOMIN5** [comment]
its just leak

**Comment by ProfKambing** [comment]
lmao

**Comment by master7720** [comment]
> ok you didnt even crack anything 😆 😆 😆 😆

```Not Cracked by FaxHack™#1211 "Yet" !!!!``` your a dumbass he said its just a leak
